# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Richard Case
tagline:          ''
description:      ''
url:              http://blog.richardcase.me
baseurl:          /

author:
  name:           'Richard Case'
  url:            https://github.com/richardcase/

timezone: <timezone>
exclude: ['Gemfile', 'Gemfile.lock', '*.sublime-*', 'lib','vendor', 'Rakefile', 's3_website.yml']

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/richardcase/
